FROM node:6
MAINTAINER na@gmail.com

RUN apt-get -y install nano

RUN curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update; apt-get -y remove cmdtest

RUN apt-get update; apt-get -y install yarn
RUN curl -sL http://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update; apt-get -y install nodejs

ENV PYTHONSERVICE_URI http://localhost:7101
ENV RSERVICE_URI http://localhost:7103
ENV DATASTORE_URI http://localhost:7102
ENV RACKETSERVICE_URI http://localhost:7104

RUN mkdir app
ADD . /app

WORKDIR /app
RUN yarn; yarn build;
RUN npm install http-server -g

EXPOSE 8080
