version: '3'
services:
  wrattler_client:
    container_name: wrattler_wrattler_client_1
    build:
      context: client
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    # stdin_open: true
    # tty: true
    depends_on:
    - wrattler_python_service
    - wrattler_data_store
    networks:
    - wrattler_nw
    volumes:
      - ./client:/app
      - ./client/src:/app/src
      - ./client/src/languagePlugins:/app/src/languagePlugins
    entrypoint: /bin/bash
    command: "./entrypoint.sh"
    environment:
     - PYTHONSERVICE_URI=http://localhost:7101
     - RSERVICE_URI=http://localhost:7103
     - DATASTORE_URI=http://localhost:7102

  wrattler_python_service:
    container_name: wrattler_wrattler_python_service_1
    build:
      context: server/python
      dockerfile: Dockerfile
    ports:
    - "7101:7101"
    environment:
     - FLASK_CONFIGURATION=default
     - DATASTORE_URI=http://wrattler_wrattler_data_store_1:7102
    networks:
    - wrattler_nw

  wrattler_r_service:
    container_name: wrattler_wrattler_r_service_1
    build:
      context: server/R
      dockerfile: Dockerfile
    ports:
    - "7103:7103"
    environment:
      - DATASTORE_URI=http://wrattler_wrattler_data_store_1:7102
      - R_SERVICE_DEBUG=True
    networks:
    - wrattler_nw

  wrattler_data_store:
    container_name: wrattler_wrattler_data_store_1
    build:
      context: server/data-store
      dockerfile: Dockerfile
    ports:
    - "7102:7102"
    networks:
    - wrattler_nw

networks:
  wrattler_nw:
    driver: bridge
