FROM ubuntu:18.04

### get pip git etc

RUN apt-get update; apt-get install -y python3
RUN apt-get update; apt-get install -y python3-pip
RUN apt-get update; apt-get install -y locales
RUN apt-get update; apt-get install -y libcairo2-dev
RUN apt-get update; apt-get install -y git

# Set the locale
RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8


RUN pip3 install  flask
RUN pip3 install flask_restful
RUN pip3 install  flask_cors
RUN pip3 install requests
RUN pip3 install pandas
RUN pip3 install pytest
RUN pip3 install scikit-learn
RUN pip3 install matplotlib
RUN pip3 install pycairo
RUN pip3 install sklearn
RUN pip3 install pandas
RUN pip3 install numpy
RUN pip3 install poetry
RUN apt-get install -y python3-venv
## install the CleverCSV AI helper
RUN git clone https://github.com/alan-turing-institute/CleverCSV
RUN cd CleverCSV/python; poetry install; pip3 install .
## install the ptype type-checker
RUN git clone https://3450c4ab25400217c11bd01021e7f89a40d2bbc7@github.com/alan-turing-institute/ptype.git
RUN cd ptype; git checkout wrattler-integration; cd src; python3 setup.py install;
## set environment variables so ptype can find data
ENV PTYPE_BROADBAND_DATA=/app/panellist-data.csv
ENV PTYPE_OUTPUT_ROOT=/tmp/
ENV PTYPE_HES_DATA=/app/appliance_data.csv
ENV PTYPE_CLEANEHR_DATA=/app/anon_public_demographic.csv
ENV PTYPE_TUNDRA_DATA=/app/teamtraits_long_AllTraits_AllObs_LongFormat.csv
ADD . /app
WORKDIR /app
